# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
relative_permalinks: False

# Setup
title:            "Gonzalo Velarde"
tagline:          'Just for fun'
description:      '***'
url:              https://gonzalovelarde.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gonzalovelarde/gonzalovelarde.github.io
